### PR TITLE
LPS-84857 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @simonjhy 

See this comment from Brian Chan
https://github.com/brianchandotcom/liferay-portal/pull/64590#issuecomment-433533758

Can you make the changes requested and resend it to me?  Thanks!

**Comment by gamerson** [comment]
hey @simonjhy   any update on this?  can you make those changes and resend back to me?

**Comment by simonjhy** [comment]
Yes, I will do it today

**Comment by simonjhy** [comment]
Just started reviewing :)

**Pull request closed without merging**
