### PR TITLE
LPS-114901 Fix the bug when handling filename

### PR DESCRIPTION
**Pull request by Seiphon**

### CODE REVIEW

**Comment by simonjhy** [comment]
Just started reviewing :)

**Comment by simonjhy** [comment]
Just started reviewing :)

**Comment by Seiphon** [comment]
Hi @simonjhy , I have sent a commit to add junit test for this issue.

**Comment by simonjhy** [comment]
Just started reviewing :)

**Comment by simonjhy** [comment]
Just started reviewing :)

**Comment by simonjhy** [comment]
sent to greg, thanks

**Pull request closed without merging**
